### PR TITLE
chore: improve python workflow

### PR DESCRIPTION
**Pull request by GoodluckH**
In tangent with https://github.com/Arrow-air/tools/pull/25

### CODE REVIEW

**Review by owlot — CHANGES_REQUESTED** [review]
You will also need to update the `SANITYCHECKS_IMAGE_TAG` in the main.mk file to match the latest image containing autopep8 (once the tools pr is merged).
Otherwise, this will fail all sanity-check workflows.

**Comment by GoodluckH** [comment]
> c0d83b6

[c0d83b6](https://github.com/Arrow-air/tf-github/pull/103/commits/c0d83b66cb942f9898f4cbfb6de0407187c83b7c)

**Comment by GoodluckH** [comment]
> You will also need to update the `SANITYCHECKS_IMAGE_TAG` in the main.mk file to match the latest image containing autopep8 (once the tools pr is merged). Otherwise, this will fail all sanity-check workflows.

[c0d83b6](https://github.com/Arrow-air/tf-github/pull/103/commits/c0d83b66cb942f9898f4cbfb6de0407187c83b7c)

**Comment by GoodluckH** [comment]
@owlot this should be good to go.

**Review by owlot — APPROVED** [review]

**Review by ServiceDog — APPROVED** [review]

**Pull request merged**
