### PR TITLE
add contributing guide

### PR DESCRIPTION
**Pull request by romanmandryk**

### CODE REVIEW

**Comment by owlot** [comment]
For dw-329 we want do have the `CONTRIBUTING.md` file added to all repositories through Terraform. This pr only adds it to the tf-github repository itself.
Could you move it to the `src/templates/all/` directory and add it to `src/main.tf` in the files map?

**Review by owlot — COMMENTED** [review]
For dw-329 we want do have the `CONTRIBUTING.md` file added to all repositories through Terraform. This pr only adds it to the tf-github repository itself.
Could you move it to the `src/templates/all/ `directory and add it to `src/main.tf` in the files map?

**Comment by romanmandryk** [comment]
I fixed the path and config file.

**Review by ServiceDog — DISMISSED** [review]

**Review by GoodluckH — DISMISSED** [review]

**Comment by owlot** [comment]
@romanmandryk Can you:
- make sure you have gpgsign set to true in your git config (your commits are unsigned)
- rebase from main
- squash your 3 commits into 1

**Comment by GoodluckH** [comment]
@romanmandryk Looks call good. Can you [retro-sign](https://superuser.com/a/1123928) your commits so that we can merge this?

**Review by GoodluckH — APPROVED** [review]

**Review by owlot — APPROVED** [review]

**Pull request merged**
